$background = 11150c
$foreground = e1e4d5

$primary = ffb0cb
$secondary = a7d0b6
$tertiary = aed197
$surface = 11150c
$surface_bright = 363b30
$outline = 8c9380
$error = 000000

$shadow = 000000

$red = bec2ff
$green = ffb2bc
$yellow = ffb0cf
$blue = 99d597
$magenta = 81d1f6
$cyan = ffb876
$white = e8c261
$red_dim = 000000
$green_dim = 000000
$yellow_dim = 000000
$blue_dim = 000000
$magenta_dim = 000000
$cyan_dim = 000000
