$background = 12131a
$foreground = e3e1ec

$primary = 9bd595
$secondary = eeb8ca
$tertiary = bec3fa
$surface = 12131a
$surface_bright = 383841
$outline = 8f8f9f
$error = 000000

$shadow = 000000

$red = 9ccaff
$green = ffb59c
$yellow = ffb1c0
$blue = 91d6a0
$magenta = 72d6d9
$cyan = e5c361
$white = e8c261
$red_dim = 000000
$green_dim = 000000
$yellow_dim = 000000
$blue_dim = 000000
$magenta_dim = 000000
$cyan_dim = 000000
