$background = 1a1209
$foreground = f1dfd0

$primary = c9bfff
$secondary = d6c68e
$tertiary = f1bd7a
$surface = 1a1209
$surface_bright = 42372d
$outline = a28d79
$error = 000000

$shadow = 000000

$red = bcc2ff
$green = ffb2bf
$yellow = f7b0e9
$blue = 7ad7bf
$magenta = 81d1f6
$cyan = ffb876
$white = e8c261
$red_dim = 000000
$green_dim = 000000
$yellow_dim = 000000
$blue_dim = 000000
$magenta_dim = 000000
$cyan_dim = 000000
